config/routes.rb
Super::Application.routes.draw do

  resources :attendees

	resources :people

	match 'photo-gallery' => 'pages#show_gallery'	
	match '*section/photo-gallery' => 'pages#show_gallery'	
	
	match 'where-we-work' => 'pages#show_map'	
	match '*section/where-we-work' => 'pages#show_map'	
	
	match 'new-person' => 'person#newsletter'
	
	match 'twFeed' => 'application#twFeed', :as => :tweets
	
	

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	belongs_to :events
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  
  # GET /attendees
  # GET /attendees.xml
  def index
    @attendees = Attendee.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @attendees }
    end
  end

  # GET /attendees/1
  # GET /attendees/1.xml
  def show
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @attendee }
    end
  end

  # GET /attendees/new
  # GET /attendees/new.xml
  def new
    @attendee = Attendee.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @attendee }
    end
  end

  # GET /attendees/1/edit
  def edit
    @attendee = Attendee.find(params[:id])
  end

  # POST /attendees
  # POST /attendees.xml
  def create
    @attendee = Attendee.new(params[:attendee])

    respond_to do |format|
      if @attendee.save
      	format.html { redirect_to "/thank-you-for-registering" }
        #format.html { redirect_to(@attendee, :notice => 'Attendee was successfully created.') }
        format.xml  { render :xml => @attendee, :status => :created, :location => @attendee }
      else
        #format.html { render :action => "new" }
        format.html { redirect_to "/thank-you-for-registering" }
        format.xml  { render :xml => @attendee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /attendees/1
  # PUT /attendees/1.xml
  def update
    @attendee = Attendee.find(params[:id])

    respond_to do |format|
      if @attendee.update_attributes(params[:attendee])
        format.html { redirect_to(@attendee, :notice => 'Attendee was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @attendee.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /attendees/1
  # DELETE /attendees/1.xml
  def destroy
    @attendee = Attendee.find(params[:id])
    @attendee.destroy

    respond_to do |format|
      format.html { redirect_to("/refinery/events") }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/views/attendees/_form.html.erb
<%= form_for(@attendee) do |f| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
      <% @attendee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br />
    <%= f.text_field :event_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>

<%= render 'form' %>

<%= link_to 'Show', @attendee %> |
<%= link_to 'Back', attendees_path %>

app/views/attendees/index.html.erb
<h1>Listing attendees</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Event</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @attendees.each do |attendee| %>
  <tr>
    <td><%= attendee.name %></td>
    <td><%= attendee.email %></td>
    <td><%= attendee.event_id %></td>
    <td><%= link_to 'Show', attendee %></td>
    <td><%= link_to 'Edit', edit_attendee_path(attendee) %></td>
    <td><%= link_to 'Destroy', attendee, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Attendee', new_attendee_path %>

app/views/attendees/new.html.erb
<h1>New attendee</h1>

<%= render 'form' %>

<%= link_to 'Back', attendees_path %>

app/views/attendees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @attendee.name %>
</p>

<p>
  <b>Email:</b>
  <%= @attendee.email %>
</p>

<p>
  <b>Event:</b>
  <%= @attendee.event_id %>
</p>


<%= link_to 'Edit', edit_attendee_path(@attendee) %> |
<%= link_to 'Back', attendees_path %>